[project]
name = "guardians-bot"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "aiogram>=3.31.0",
    "fastapi>=0.141.0",
    "redis>=6.4.0",
    "pydantic-settings>=2.15.0",
    "httpx==0.28.1",
    "pydantic==2.13.5"
]

[tool.vercel]
entrypoint = "api.index:app"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["app*"]
